name: Publish Release

on:
  push:
    tags:
      - 'v*' # This triggers the workflow when you push a tag like 'v1.0.1'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build zip
        run: |
          zip -r "Ai-Assistant.zip" . -x "*.git*" "*.github*" "images/*" ".*"

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: "Ai-Assistant.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
