name: Plugins manifest validation

on:
  push:
    paths:
      - 'plugins/*.json'
  pull_request:
    paths:
      - 'plugins/*.json'
  workflow_dispatch:

jobs:
  skip_check_job:
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.filter.outputs.plugins }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            plugins:
              - "plugins/*.json"
  test:
    needs: skip_check_job
    if: ${{ needs.skip_check_job.outputs.plugins == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r ./ci/envs/requirements-validator.txt

      - name: Test with pytest
        run: |
          pytest ./ci/src/validator.py
