name: VirusTotal Scan

on:
  workflow_dispatch:
  pull_request:
    paths:
      - plugins/**
  push: #<=============

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up Go
      #   uses: actions/setup-go@v4

      - name: Download All Plugins
        run: |
          pip install -r ci/envs/requirements-virustotal-setup.txt
          python ./ci/src/virustotal_setup.py

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        id: vt
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./VirusTotal_Tests/*

      - name: 'Echo Analysis Links'
        run: echo ${{ steps.vt.outputs.analysis }}