name: Deploy Website

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            https://api.github.com/repos/Flow-Launcher/flow-launcher.github.io/dispatches \
            -d '{"event_type":"deploy"}'
